import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, PageBreak
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib.units import cm
from reportlab.lib import colors

# ──────────────────────────────────────────────
# Estilos globales
# ──────────────────────────────────────────────
styles = getSampleStyleSheet()

styles.add(ParagraphStyle(
    name='DaDaJustify',
    alignment=TA_JUSTIFY,
    fontSize=10.5,
    leading=15,
    spaceAfter=6,
))
styles.add(ParagraphStyle(
    name='DaDaH2',
    alignment=TA_LEFT,
    fontSize=13,
    leading=16,
    spaceAfter=6,
    spaceBefore=14,
    fontName="Helvetica-Bold",
))
styles.add(ParagraphStyle(
    name='DaDaH3',
    alignment=TA_LEFT,
    fontSize=11,
    leading=14,
    spaceAfter=4,
    spaceBefore=10,
    fontName="Helvetica-Bold",
))
styles.add(ParagraphStyle(
    name='DaDaCenter',
    alignment=TA_CENTER,
    fontSize=10,
    leading=13,
    spaceAfter=4,
    textColor=colors.HexColor("#444444"),
))
styles.add(ParagraphStyle(
    name='DaDaBullet',
    alignment=TA_LEFT,
    fontSize=10.5,
    leading=15,
    spaceAfter=4,
    leftIndent=24,
))


def build_story(title, subtitle, content_blocks):
    """
    Construye la lista de flowables para el documento.
    Prefijos especiales en content_blocks:
        '##'       -> H2
        '###'      -> H3
        '---'      -> Linea divisoria
        '>>>BREAK' -> Salto de pagina
        '-'        -> Bullet
    """
    story = []

    # Portada
    story.append(Spacer(1, 2 * cm))
    cover_title_style = ParagraphStyle(
        name="CoverTitle",
        fontSize=22,
        leading=28,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1A1A2E"),
    )
    story.append(Paragraph("Da&amp;Da Solutions", cover_title_style))
    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="80%", thickness=2, color=colors.HexColor("#7C3AED")))
    story.append(Spacer(1, 0.6 * cm))

    doc_title_style = ParagraphStyle(
        name="DocTitle",
        fontSize=18,
        leading=24,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#2D2D2D"),
    )
    story.append(Paragraph(title, doc_title_style))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph(subtitle, styles['DaDaCenter']))
    story.append(Spacer(1, 1.5 * cm))
    story.append(HRFlowable(width="60%", thickness=1, color=colors.HexColor("#AAAAAA")))
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph("Documento Interno — Confidencial", styles['DaDaCenter']))
    story.append(Paragraph("Version 3.1  |  Anio 2026  |  Departamento de Ingenieria", styles['DaDaCenter']))
    story.append(PageBreak())

    # Contenido
    for block in content_blocks:
        s = block.strip()
        if s == ">>>BREAK":
            story.append(PageBreak())
        elif s == "---":
            story.append(Spacer(1, 6))
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#CCCCCC")))
            story.append(Spacer(1, 6))
        elif s.startswith("###"):
            story.append(Paragraph(s[3:].strip(), styles['DaDaH3']))
        elif s.startswith("##"):
            story.append(Paragraph(s[2:].strip(), styles['DaDaH2']))
        elif s.startswith("-"):
            story.append(Paragraph("&bull; " + s[1:].strip(), styles['DaDaBullet']))
        else:
            story.append(Paragraph(s, styles['DaDaJustify']))

    return story


def create_pdf(filename, title, subtitle, content_blocks):
    """Genera un archivo PDF con portada y contenido estructurado."""
    filepath = os.path.join("docs", filename)
    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=2.2 * cm,
        leftMargin=2.2 * cm,
        topMargin=2.2 * cm,
        bottomMargin=2 * cm,
    )
    doc.build(build_story(title, subtitle, content_blocks))
    print(f"  OK  Generado: {filename}")


# ==============================================================================
#  CONTENIDOS — 7 DOCUMENTOS (~25 paginas cada uno)
# ==============================================================================

documents = [

    # --------------------------------------------------------------------------
    # 1. ONBOARDING
    # --------------------------------------------------------------------------
    {
        "filename": "onboarding.pdf",
        "title": "Manual de Onboarding para Nuevos Desarrolladores",
        "subtitle": "Tu guia completa para los primeros 90 dias en Da&Da Solutions",
        "content": [
            "## 1. Bienvenida de la Direccion",
            "Bienvenido a Da&amp;Da Solutions. Somos una empresa tecnologica fundada en 2014 con sede principal en Buenos Aires, Argentina, y oficinas en Ciudad de Mexico, Bogota y Madrid. Nuestra mision es transformar los negocios de nuestros clientes a traves de soluciones de software de alto impacto, combinando excelencia tecnica con una cultura de innovacion continua.",
            "Este documento ha sido preparado por el equipo de People &amp; Engineering para acompanarte en tus primeros 90 dias. Leelo con calma, guardalo como referencia y no dudes en consultar a tu Buddy o a tu Team Lead ante cualquier duda.",
            "Creemos firmemente en tres valores que guian todo lo que hacemos: <b>Colaboracion</b>, <b>Excelencia Tecnica</b> y <b>Responsabilidad con el Impacto</b>. Veras esos valores reflejados en cada proceso, decision de arquitectura y conversacion de equipo.",
            "---",
            "## 2. Estructura Organizacional",
            "Da&amp;Da Solutions opera bajo un modelo de organizacion matricial con equipos funcionales y squads de producto. La compania se divide en cuatro grandes areas:",
            "- <b>Engineering:</b> Backend, Frontend, Infraestructura/DevOps e Inteligencia Artificial.",
            "- <b>Product:</b> Product Managers, UX Researchers y Disenadores.",
            "- <b>Data:</b> Data Engineers, Data Scientists y Analytics Engineers.",
            "- <b>People &amp; Operations:</b> Recursos Humanos, Finanzas y Administracion.",
            "Cada Squad de producto es un equipo autonomo y multidisciplinario compuesto generalmente por 1 Product Manager, 1 UX Designer, 2-4 ingenieros Backend, 2-3 ingenieros Frontend y 1 QA Engineer. Los squads son los duenos de sus propios servicios y ciclos de releases.",
            "El organigrama completo se puede consultar en la intranet corporativa en la seccion 'Empresa - Organigrama'. La intranet esta disponible en <b>intranet.dadacode.io</b>.",
            "---",
            "## 3. Dias 1 al 7: Primera Semana",
            "### 3.1 Dia 1: Accesos y Configuracion",
            "El primer dia esta disenado para que puedas configurar tu entorno sin presion. Tu Buddy (un colega asignado especificamente para ayudarte durante el onboarding) te esperara a las 9:00 AM en la sala 'Turing' y te acompanara durante todo el dia.",
            "Las tareas del primer dia incluyen: activar tu cuenta corporativa de Google Workspace (el correo electronico con dominio @dadacode.io), configurar la autenticacion de dos factores en todos los servicios, instalar y configurar el cliente VPN corporativo (usamos Tailscale), unirte a los canales de Slack correspondientes a tu squad y obtener los accesos a los repositorios de GitHub.",
            "### 3.2 Dias 2-3: Entorno de Desarrollo",
            "Durante los dias 2 y 3 te concentraras en levantar tu entorno de desarrollo local. El proceso estandar consiste en clonar el repositorio de tu squad principal, instalar las dependencias con el gestor de paquetes correspondiente (Poetry para proyectos Python, npm/pnpm para proyectos JavaScript), y levantar el entorno completo con Docker Compose.",
            "En la raiz de cada proyecto encontraras un archivo <b>DEVELOPMENT.md</b> con instrucciones especificas. Si encuentras que las instrucciones estan desactualizadas o son confusas, se espera que, como parte del onboarding, abras un Pull Request para mejorarlas. Es una excelente primera contribucion.",
            "### 3.3 Dias 4-5: Inmerssion en el Negocio",
            "Los ultimos dos dias de la primera semana estan reservados para reuniones de contexto. Tu Team Lead coordinara sesiones de 30-45 minutos con los principales stakeholders del area, el Product Manager del squad y los referentes tecnicos de las areas con las que mas interactuaras.",
            "Tambien completaras los cursos obligatorios de la plataforma de e-learning interna: 'Seguridad de la Informacion en Da&amp;Da', 'Manejo de Datos Personales (GDPR/LGPD)' y 'Codigo de Conducta y Diversidad'. Estos cursos son obligatorios y deben completarse en los primeros 7 dias habiles.",
            "---",
            "## 4. Dias 8 al 30: Primera Mision",
            "### 4.1 El Primer Ticket",
            "Alrededor del octavo dia recibiras tu primer ticket de Jira. Hemos disenado este proceso con cuidado: el primer ticket siempre sera una tarea etiquetada como 'good-first-issue', de dificultad baja o media, elegida en conjunto con tu Team Lead para que puedas familiarizarte con el codebase, el proceso de Pull Request y el ciclo de deploy sin una presion excesiva.",
            "No se espera velocidad en esta etapa. Se espera que hagas preguntas, que leas el codigo con atencion y que entiendas el 'por que' detras de las decisiones de implementacion.",
            "### 4.2 El Proceso de Pull Request",
            "En Da&amp;Da Solutions el proceso de PR es nuestra principal herramienta de garantia de calidad y transferencia de conocimiento. Todo cambio de codigo, sin excepcion, debe pasar por un Pull Request. Los PRs deben:",
            "- Tener un titulo descriptivo usando el formato: [TIPO]: descripcion corta. Ejemplo: [FEAT]: agregar endpoint de renovacion de suscripcion.",
            "- Incluir una descripcion del cambio, el ticket de Jira relacionado y capturas de pantalla para cambios de UI.",
            "- Pasar todos los checks automaticos del pipeline de CI (linters, tests, analisis de seguridad).",
            "- Recibir aprobacion de al menos dos revisores antes de hacer merge.",
            "- No puede tener mas de 400 lineas de cambio. Los PRs grandes deben dividirse.",
            "### 4.3 Ciclo de Reuniones del Squad",
            "El squad opera bajo un framework agil inspirado en Scrum con sprints de dos semanas. Las ceremonias son:",
            "- <b>Daily Standup</b> (15 minutos, todos los dias a las 10:00 AM): Que hice ayer, que hare hoy, hay algun bloqueante.",
            "- <b>Sprint Planning</b> (2 horas, primer dia del sprint): Se definen los objetivos del sprint y se estiman las tareas.",
            "- <b>Sprint Review</b> (1 hora, ultimo dia del sprint): Se presentan los resultados a los stakeholders.",
            "- <b>Retrospectiva</b> (45 minutos, ultimo dia del sprint): Discusion interna del equipo sobre que mejorar.",
            "- <b>Refinamiento</b> (1 hora a mitad del sprint): Se prepara el backlog para el proximo sprint.",
            "---",
            "## 5. Herramientas Corporativas",
            "### 5.1 Comunicacion: Slack",
            "Slack es nuestra herramienta principal de comunicacion asincrona. Algunos canales clave a los que debes unirte desde el primer dia:",
            "- <b>#anuncios-generales</b>: Comunicados oficiales de la empresa.",
            "- <b>#ingenieria</b>: Canal general del departamento de Engineering.",
            "- <b>#ayuda-tecnica</b>: Canal para hacer preguntas tecnicas a la comunidad.",
            "- <b>#deployments</b>: Notificaciones automaticas de todos los deployments a produccion.",
            "- <b>#incidentes</b>: Alertas criticas y coordinacion de respuesta a incidentes.",
            "- <b>#random</b>: Conversaciones informales, memes y cultura de empresa.",
            "### 5.2 Gestion de Proyectos: Jira",
            "Jira es nuestra herramienta de gestion de tareas y seguimiento de proyectos. Cada squad tiene su propio tablero. Los tickets tienen los siguientes estados: Backlog, To Do, In Progress, In Review, QA y Done.",
            "Cada ticket debe tener: descripcion clara con criterios de aceptacion, estimacion en Story Points (usando la escala de Fibonacci: 1, 2, 3, 5, 8, 13), etiquetas de tipo (Bug, Feature, Tech Debt, etc.) y enlace al Pull Request una vez que se inicie el desarrollo.",
            "### 5.3 Documentacion: Confluence",
            "La documentacion tecnica y de producto vive en Confluence. Cada squad tiene su propio espacio. Se espera que todo desarrollador contribuya activamente a la documentacion: si resuelves un problema dificil, documentalo; si descubres un comportamiento no documentado, documentalo.",
            "### 5.4 Control de Versiones: GitHub",
            "Toda la organizacion vive en la GitHub Organization <b>dada-solutions</b>. El acceso a repositorios es gestionado por el equipo de Platform Engineering. El branching model estandar es <b>GitHub Flow</b>: ramas de features efimeras que se crean desde main y se mergean de vuelta a main mediante PR.",
            "---",
            "## 6. Entorno de Desarrollo Local",
            "### 6.1 Hardware y Software Recomendado",
            "Da&amp;Da Solutions proporciona a todos sus empleados tecnicos una laptop corporativa con las siguientes especificaciones minimas: procesador de 8 nucleos, 16 GB de RAM (32 GB recomendados para microservicios), 512 GB SSD NVMe. El sistema operativo es a eleccion: macOS, Ubuntu 22.04 LTS o Windows 11 con WSL2.",
            "### 6.2 IDEs y Extensiones",
            "Los IDEs mas usados son VS Code y JetBrains (IntelliJ IDEA, PyCharm, WebStorm). Para VS Code, el equipo mantiene un archivo <b>.vscode/extensions.json</b> en todos los repositorios con las extensiones recomendadas. Las mas importantes son: ESLint, Prettier, Python, Docker y GitLens.",
            "### 6.3 Docker y Docker Compose",
            "Todos los proyectos estan contenerizados. El archivo <b>docker-compose.yml</b> en la raiz de cada proyecto es la forma estandar de levantar el entorno de desarrollo. El comando habitual es: docker compose up -d --build. Este comando levantara todos los servicios necesarios: la aplicacion principal, las bases de datos y cualquier servicio dependiente.",
            "### 6.4 Variables de Entorno",
            "Nunca se deben commitear variables de entorno con valores reales al repositorio. Cada proyecto tiene un archivo <b>.env.example</b> con todas las variables necesarias pero sin valores sensibles. Para el entorno local, se debe crear un archivo <b>.env</b> copiando el .env.example y completando con los valores correspondientes. Los valores de desarrollo estan disponibles en el vault de 1Password del equipo.",
            "---",
            "## 7. Dias 31 al 90: Crecimiento Autonomo",
            "### 7.1 Asumiendo Responsabilidades",
            "A partir del segundo mes se espera que el nuevo integrante empiece a asumir tareas de manera mas autonoma. El rol del Buddy comienza a disminuir y se espera que el desarrollador se convierta en un ciudadano activo del squad: participando en el refinamiento, proponiendo mejoras tecnicas y contribuyendo a las revisiones de codigo.",
            "### 7.2 Revisiones de Codigo como Revisor",
            "Se espera que a partir de la cuarta semana el nuevo integrante empiece a hacer revisiones de PRs de sus companeros. Las revisiones deben ser constructivas, especificas y empaticas. Nunca se critica a la persona; siempre se discute el codigo.",
            "### 7.3 La Evaluacion de los 90 Dias",
            "Al finalizar los 90 dias de onboarding, el Team Lead y el Manager realizaran una evaluacion formal de 360 grados. En ella se evaluaran competencias tecnicas (calidad de codigo, comprension de la arquitectura, velocidad de aprendizaje), competencias blandas (comunicacion, colaboracion, actitud ante el feedback) y alineacion con los valores de la empresa.",
            "Esta evaluacion no tiene el objetivo de ser un examen, sino una conversacion honesta para definir un plan de carrera y los proximos objetivos de desarrollo para el siguiente trimestre.",
            "---",
            "## 8. Cultura y Valores",
            "### 8.1 Diversidad e Inclusion",
            "Da&amp;Da Solutions esta comprometida activamente con construir un equipo diverso e inclusivo. Tenemos una politica de tolerancia cero ante cualquier forma de discriminacion, acoso o comportamiento excluyente. Si eres testigo o victima de cualquier situacion de este tipo, puedes reportarla de forma anonima a traves del canal etico en la intranet.",
            "### 8.2 Work-Life Balance",
            "Creemos que las personas producen mejor cuando estan descansadas y equilibradas. Nuestra politica de trabajo es <b>async-first</b>: priorizamos la comunicacion asincrona y respetamos los horarios personales. No se espera que nadie responda mensajes fuera de su horario laboral. Las guardias de produccion son compensadas con tiempo libre adicional.",
            "### 8.3 Aprendizaje Continuo",
            "Cada empleado tecnico tiene acceso a un presupuesto anual de desarrollo profesional de USD 1.200 para cursos, libros, conferencias y certificaciones. Ademas, cada viernes de 4:00 PM a 6:00 PM es tiempo protegido para aprendizaje: no se programan reuniones y se espera que los desarrolladores usen ese tiempo en actividades de formacion o exploracion tecnica.",
            "---",
            "## 9. Preguntas Frecuentes",
            "### Como solicito vacaciones?",
            "Las vacaciones se solicitan a traves del modulo de Recursos Humanos en la intranet con al menos 15 dias de anticipacion. El Team Lead debe aprobar la solicitud. La politica de vacaciones es de 15 dias habiles anuales para empleados de 0 a 2 anios de antiguedad, y 20 dias habiles para empleados con mas de 2 anios.",
            "### Que hago si encuentro una vulnerabilidad de seguridad?",
            "Reporta inmediatamente al canal #seguridad en Slack y envia un correo a security@dadacode.io con el asunto 'SECURITY REPORT'. No crees un ticket de Jira publico. El equipo de Security Engineering te contactara en menos de 4 horas.",
            "### Como escalo un incidente en produccion?",
            "Primero notifica en el canal #incidentes de Slack con el prefijo [P1], [P2] o [P3] segun la severidad. El runbook de incidentes esta documentado en Confluence en la seccion 'Engineering - Operaciones - Runbooks'. P1 requiere notificacion inmediata al On-Call Engineer mediante PagerDuty.",
            "### Puedo trabajar en remoto?",
            "Si. Da&amp;Da Solutions tiene una politica de trabajo hibrido flexible. Se espera presencia en oficina de 2 dias a la semana, preferentemente los martes y jueves que son los dias de maxima presencia del equipo.",
            "---",
            "## 10. Recursos y Contactos Clave",
            "- <b>IT Helpdesk:</b> helpdesk@dadacode.io | Slack: #it-helpdesk",
            "- <b>People &amp; HR:</b> people@dadacode.io | Slack: #people-hr",
            "- <b>Seguridad:</b> security@dadacode.io | Slack: #seguridad",
            "- <b>Intranet:</b> intranet.dadacode.io",
            "- <b>Confluence (Documentacion):</b> docs.dadacode.io",
            "- <b>Jira (Gestion de tareas):</b> jira.dadacode.io",
            "- <b>GitHub Org:</b> github.com/dada-solutions",
        ],
    },

    # --------------------------------------------------------------------------
    # 2. BACKEND GUIDE
    # --------------------------------------------------------------------------
    {
        "filename": "backend_guide.pdf",
        "title": "Guia Oficial de Ingenieria Back-end",
        "subtitle": "Estandares, patrones y mejores practicas para el desarrollo de servicios en Da&Da Solutions",
        "content": [
            "## 1. Introduccion y Filosofia",
            "Esta guia es el documento de referencia para todos los ingenieros de Back-end de Da&amp;Da Solutions. Establece los estandares que deben seguirse en el diseno, desarrollo, testing y mantenimiento de todos los servicios de la compania. No es una sugerencia: el cumplimiento de estas guias es parte de los criterios de aceptacion de cada Pull Request.",
            "Nuestra filosofia de ingenieria back-end se resume en tres principios: <b>Simplicidad ante todo</b> (el codigo simple es mas facil de mantener, testear y escalar), <b>APIs como productos</b> (cada API que construimos es un producto con sus propios consumidores; debe ser confiable, versionada y bien documentada) y <b>Operabilidad desde el dia uno</b> (todo servicio debe nacer con metricas, logs estructurados y health checks).",
            "---",
            "## 2. Stack Tecnologico Oficial",
            "### 2.1 Python con FastAPI",
            "FastAPI es nuestro framework principal para servicios orientados a datos, APIs de alto rendimiento y todos los servicios relacionados con Inteligencia Artificial. FastAPI se elige por su rendimiento (basado en Starlette y Uvicorn, con soporte nativo de async/await), su sistema de validacion de datos basado en Pydantic y su generacion automatica de documentacion OpenAPI.",
            "La version minima soportada es Python 3.11. Para la gestion de dependencias usamos <b>Poetry</b>. El archivo pyproject.toml es la fuente de verdad de las dependencias.",
            "### 2.2 Node.js con NestJS",
            "NestJS es nuestro framework estandar para servicios Node.js. Se prefiere para servicios con logica de negocio compleja gracias a su arquitectura modular basada en decoradores y su sistema de inyeccion de dependencias. La version LTS activa de Node.js es la obligatoria. Para TypeScript, el tsconfig.json corporativo con strict mode activado esta disponible en el repositorio de plantillas.",
            "### 2.3 Go para Servicios de Alta Performance",
            "Go se utiliza selectivamente para servicios que requieren latencias extremadamente bajas o un alto nivel de concurrencia, como el API Gateway o ciertos workers de procesamiento de eventos. El uso de Go en nuevos servicios requiere aprobacion del Staff Engineer del area.",
            "---",
            "## 3. Estandares de Diseno de API REST",
            "### 3.1 Versionado",
            "Todas las APIs publicas deben estar versionadas en la URL. El formato es /api/v{N}/recurso. Actualmente, las APIs nuevas comienzan en v1. Un cambio de version mayor solo se justifica ante breaking changes. Los cambios backward-compatible (agregar campos opcionales, nuevos endpoints) no requieren cambio de version.",
            "### 3.2 Convenciones de Nomenclatura",
            "Los recursos en la URL deben ser sustantivos en plural y en minusculas, separados por guiones: /api/v1/user-profiles. Los verbos HTTP indican la accion: GET para leer, POST para crear, PUT/PATCH para actualizar y DELETE para eliminar.",
            "Los nombres de campos en el body JSON deben usar snake_case. Ejemplo: { first_name: Maria, last_name: Gonzalez, created_at: 2026-01-15T10:30:00Z }.",
            "### 3.3 Estructura de Respuesta Estandarizada",
            "Todas las respuestas de la API deben seguir un envelope estandar. Para respuestas exitosas: { success: true, data: {...}, meta: { page: 1, total: 150 } }. Para respuestas de error: { success: false, data: null, error: { code: USER_NOT_FOUND, message: El usuario con id 123 no fue encontrado. } }.",
            "### 3.4 Paginacion",
            "Todo endpoint que retorna colecciones debe implementar paginacion. Se prefiere cursor-based para colecciones grandes. Los parametros estandar para offset-based son: page (numero de pagina, default 1) y page_size (tamano de pagina, default 20, maximo 100).",
            "### 3.5 Filtrado y Ordenamiento",
            "Los endpoints de listado deben soportar filtros a traves de query params. El ordenamiento se especifica con sort_by (campo) y sort_order (asc/desc). Ejemplo: /api/v1/orders?status=pending&amp;sort_by=created_at&amp;sort_order=desc.",
            "---",
            "## 4. Autenticacion y Autorizacion",
            "### 4.1 JSON Web Tokens (JWT)",
            "Toda la autenticacion de usuarios en Da&amp;Da Solutions se basa en JWT. El Access Token tiene un tiempo de vida de 15 minutos. El Refresh Token tiene un tiempo de vida de 7 dias y debe almacenarse en una cookie HttpOnly Secure para prevenir ataques XSS.",
            "El Access Token debe enviarse en el header HTTP: Authorization: Bearer token. Los servicios internos validan el token usando la clave publica del servicio de autenticacion (auth-service) a traves de JWKS (JSON Web Key Sets).",
            "### 4.2 Roles y Permisos (RBAC)",
            "Implementamos un sistema de Control de Acceso Basado en Roles (RBAC). Los roles principales son: SUPER_ADMIN, ADMIN, MANAGER, DEVELOPER, VIEWER. Las reglas de autorizacion deben implementarse a nivel de servicio, no solo en el API Gateway. El API Gateway verifica la autenticacion; los servicios individuales verifican la autorizacion.",
            "### 4.3 API Keys para Servicios Internos",
            "La comunicacion servicio-a-servicio usa API Keys estaticas que se almacenan en el vault secreto (HashiCorp Vault). Estas keys se rotan cada 90 dias de forma automatica. Nunca se deben hardcodear API Keys en el codigo fuente.",
            "---",
            "## 5. Manejo de Errores y Excepciones",
            "### 5.1 Principio General",
            "El codigo debe manejar los errores de forma explicita. Nunca debe silenciarse una excepcion con un try/except/catch vacio. Si se captura una excepcion, debe loggearse con contexto suficiente para poder diagnosticar el problema en produccion.",
            "### 5.2 Errores de Negocio vs Errores de Sistema",
            "Es fundamental distinguir entre errores de negocio (validacion fallida, recurso no encontrado, permisos insuficientes) y errores de sistema (base de datos no disponible, servicio externo caido, error de red). Los primeros se traducen en respuestas HTTP 4xx; los segundos en respuestas HTTP 5xx.",
            "### 5.3 Error Codes Estandar",
            "Cada dominio de negocio tiene un catalogo de error codes. El formato es DOMAIN_ERROR_NAME en mayusculas con guiones bajos. Ejemplos: AUTH_INVALID_CREDENTIALS, USER_EMAIL_ALREADY_EXISTS, PAYMENT_INSUFFICIENT_FUNDS, ORDER_ITEM_OUT_OF_STOCK. El catalogo completo vive en Confluence.",
            "---",
            "## 6. Testing",
            "### 6.1 Piramide de Testing",
            "Seguimos la piramide de testing: muchos tests unitarios en la base, tests de integracion en el medio, y pocos tests end-to-end en la cima. La cobertura minima requerida para mergear a main es del 80% en tests unitarios.",
            "### 6.2 Tests Unitarios",
            "Para Python usamos pytest con los plugins pytest-asyncio y pytest-cov. Para NestJS usamos Jest con el framework de testing incorporado. Los tests deben ser aislados: nunca deben depender de una base de datos real o un servicio externo real; se usan mocks y stubs.",
            "### 6.3 Tests de Integracion",
            "Los tests de integracion verifican que los componentes internos funcionen correctamente juntos. Pueden conectarse a bases de datos reales pero en contenedores efimeros usando testcontainers. Se ejecutan en el pipeline de CI pero no bloquean los entornos de produccion.",
            "### 6.4 Contract Testing con Pact",
            "Para verificar la compatibilidad entre servicios que se comunican, usamos Pact (contract testing). El Consumer define el contrato de lo que espera y el Provider verifica que lo cumple. Esto previene que cambios en un servicio rompan silenciosamente a sus consumidores.",
            "---",
            "## 7. Observabilidad",
            "### 7.1 Logs Estructurados",
            "Todos los servicios deben generar logs en formato JSON estructurado. Los campos obligatorios son: timestamp (ISO 8601), level (DEBUG, INFO, WARNING, ERROR, CRITICAL), service_name, trace_id, span_id y message. El trace_id es esencial para correlacionar logs de distintos servicios en una misma request.",
            "Para Python usamos structlog. Para NestJS usamos pino con pino-pretty para desarrollo local.",
            "### 7.2 Metricas con Prometheus",
            "Cada servicio debe exponer un endpoint /metrics en formato Prometheus. Las metricas obligatorias son: latencia de endpoints (histograma), tasa de errores (counter), throughput de requests (counter) y metricas de recursos del proceso (CPU, memoria).",
            "### 7.3 Tracing Distribuido con OpenTelemetry",
            "Todos los servicios deben instrumentarse con OpenTelemetry para tracing distribuido. Los traces se exportan a nuestro backend de observabilidad (Jaeger en staging, Tempo en produccion). El trace_id debe propagarse en todos los headers HTTP de comunicacion inter-servicio usando el estandar W3C Trace Context.",
            "### 7.4 Health Checks",
            "Cada servicio debe implementar dos endpoints: /health/liveness (verifica que el proceso esta corriendo) y /health/readiness (verifica que el servicio puede manejar trafico, incluyendo conectividad a bases de datos). Kubernetes usa estos endpoints para el manejo del ciclo de vida del pod.",
            "---",
            "## 8. Seguridad",
            "### 8.1 OWASP Top 10",
            "Todos los desarrolladores back-end deben conocer el OWASP Top 10. Las vulnerabilidades mas criticas en nuestro contexto son: Injection (SQL Injection, NoSQL Injection — siempre usar queries parametrizadas u ORMs), Broken Authentication (nunca almacenar passwords en texto plano, usar bcrypt con salt rounds minimo 12) y Cryptographic Failures (no usar MD5 o SHA1 para passwords).",
            "### 8.2 Analisis Estatico de Seguridad (SAST)",
            "El pipeline de CI incluye un analisis de seguridad estatico con Bandit (Python) y Semgrep (multi-lenguaje). Un hallazgo de severidad HIGH o CRITICAL en una PR bloquea el merge hasta ser resuelto o marcado como falso positivo con justificacion.",
            "### 8.3 Gestion de Secretos",
            "Nunca se deben almacenar secretos (contrasenas, API keys, certificados) en variables de entorno del sistema operativo ni en el codigo fuente. En produccion, todos los secretos son inyectados desde HashiCorp Vault al momento de iniciar el contenedor.",
            "---",
            "## 9. Performance y Optimizacion",
            "### 9.1 Async por defecto",
            "En FastAPI y NestJS, las funciones de handler de endpoints deben ser async/await por defecto para aprovechar el event loop y no bloquear el thread mientras se esperan operaciones de I/O (consultas a base de datos, llamadas a APIs externas).",
            "### 9.2 Database Query Optimization",
            "Se debe monitorear el rendimiento de las queries de base de datos desde el principio. Reglas basicas: nunca hacer N+1 queries (siempre usar eager loading o batch fetching), crear indices en los campos usados en clausulas WHERE y JOIN, y usar EXPLAIN/EXPLAIN ANALYZE para entender el plan de ejecucion.",
            "### 9.3 Cache",
            "Antes de agregar cache, medir. La cache introduce complejidad (invalidacion, consistencia eventual). Solo agregar cache cuando los datos de perfilado demuestren un cuello de botella claro. Cuando se usa Redis para cache, establecer siempre un TTL explicito para evitar acumulacion de memoria.",
            "---",
            "## 10. Releases y Versionado Semantico",
            "Todos los servicios siguen Semantic Versioning (SemVer): MAJOR.MINOR.PATCH. Un MAJOR bump indica breaking changes en la API publica. Un MINOR bump indica funcionalidad nueva backward-compatible. Un PATCH bump indica correcciones de bugs backward-compatible.",
            "Los changelogs se generan automaticamente desde los mensajes de commit usando Conventional Commits y la herramienta semantic-release. Los mensajes de commit deben seguir el formato: type(scope): description. Tipos validos: feat, fix, docs, style, refactor, test, chore.",
        ],
    },

    # --------------------------------------------------------------------------
    # 3. FRONTEND GUIDE
    # --------------------------------------------------------------------------
    {
        "filename": "frontend_guide.pdf",
        "title": "Guia Oficial de Ingenieria Front-end",
        "subtitle": "Estandares, design system y mejores practicas para el desarrollo de interfaces en Da&Da Solutions",
        "content": [
            "## 1. Filosofia de Desarrollo Front-end",
            "En Da&amp;Da Solutions el front-end no es 'solo la pantalla': es el producto que el usuario ve y toca todos los dias. La calidad de la experiencia de usuario es un diferenciador competitivo directo. El equipo de Front-end opera con los mismos estandares de ingenieria que el back-end: testing riguroso, revision de codigo, observabilidad y despliegue continuo.",
            "Nuestros tres principios guias son: <b>Performance como funcionalidad</b> (una interfaz lenta es una interfaz rota), <b>Accesibilidad no es opcional</b> (todo lo que construimos debe ser usable por personas con discapacidades) y <b>Coherencia a traves del Design System</b> (la consistencia visual genera confianza).",
            "---",
            "## 2. Stack Tecnologico",
            "### 2.1 React 18 como Base",
            "React 18 es nuestro framework de UI principal. Aprovechamos las caracteristicas de React 18 al maximo: Concurrent Mode, Suspense para data fetching y Transitions para actualizaciones no urgentes de UI. El uso de Class Components esta completamente deprecado; toda la logica debe estar en componentes funcionales con hooks.",
            "### 2.2 Next.js 14 para Aplicaciones con SSR/SSG",
            "Para aplicaciones que requieren Server-Side Rendering (SSR), Static Site Generation (SSG) o que son publicamente indexadas por buscadores, usamos Next.js 14 con el App Router. El App Router de Next.js 14 es el estandar; el Pages Router esta en modo mantenimiento y no debe usarse en proyectos nuevos.",
            "### 2.3 Vite para SPAs Internas",
            "Para Single Page Applications internas (dashboards, herramientas administrativas) que no requieren SEO, usamos Vite como bundler por su velocidad de desarrollo incomparable. La plantilla corporativa de Vite + React + TypeScript esta disponible en el repositorio dada-solutions/fe-template.",
            "### 2.4 TypeScript: Obligatorio",
            "TypeScript es obligatorio en todos los proyectos front-end nuevos. El modo strict en tsconfig.json debe estar activado. El uso de any esta prohibido; si se necesita un tipo dinamico, se debe usar unknown con type narrowing explicito.",
            "---",
            "## 3. El Design System de Da&Da Solutions",
            "### 3.1 Paleta de Colores Corporativa",
            "El design system de Da&amp;Da Solutions esta construido sobre una paleta de colores oscura con acentos en purpura:",
            "- <b>Background Primary:</b> #0D0D14 (fondo principal de la aplicacion)",
            "- <b>Background Secondary:</b> #1A1A2E (fondo de tarjetas y paneles)",
            "- <b>Background Tertiary:</b> #252540 (fondo de elementos elevados)",
            "- <b>Purple Primary:</b> #7C3AED (botones primarios, acentos principales)",
            "- <b>Purple Light:</b> #A855F7 (hover states, iconos activos)",
            "- <b>Purple Subtle:</b> #2D1B69 (fondos con acento sutil)",
            "- <b>Text Primary:</b> #F0F0FF (texto principal)",
            "- <b>Text Secondary:</b> #9898C0 (texto secundario, labels)",
            "- <b>Border:</b> #2A2A4A (bordes de componentes)",
            "- <b>Success:</b> #10B981, <b>Warning:</b> #F59E0B, <b>Error:</b> #EF4444",
            "### 3.2 Tipografia",
            "La fuente principal del sistema es <b>Inter</b> (importada desde Google Fonts). La jerarquia tipografica es: H1 (32px/700), H2 (24px/600), H3 (20px/600), H4 (16px/600), Body (14px/400), Small (12px/400). El line-height estandar es 1.5 para body text y 1.2 para headings.",
            "### 3.3 Espaciado y Grid",
            "El sistema de espaciado usa una escala de base 4px: 4, 8, 12, 16, 24, 32, 48, 64, 96px. El layout usa CSS Grid para estructuras de pagina y Flexbox para alineacion de componentes. El breakpoint principal para mobile es 768px.",
            "### 3.4 Componentes del Design System",
            "El Design System esta implementado como una libreria de componentes publicada en el NPM registry privado de Da&amp;Da bajo el scope @dada. Los componentes principales incluyen: Button, Input, Select, Textarea, Modal, Drawer, Toast, Table, Badge, Avatar, Tooltip, Dropdown y FormField.",
            "Antes de crear un componente nuevo, siempre verificar si ya existe en el design system. Si no existe pero es reutilizable, la practica correcta es crearlo en el design system y no en el proyecto.",
            "---",
            "## 4. Arquitectura y Patrones de Componentes",
            "### 4.1 Estructura de Directorios",
            "La estructura estandar de un proyecto Next.js en Da&amp;Da Solutions es: /app (rutas y layouts del App Router), /components (componentes compartidos dentro del proyecto), /lib (utilidades, helpers, clientes de API), /hooks (custom hooks reutilizables), /stores (stores de Zustand), /types (definiciones de tipos TypeScript) y /styles (CSS Modules y variables globales).",
            "### 4.2 Colocation de Archivos",
            "Cada componente vive en su propia carpeta con todos los archivos relacionados: ComponentName/index.tsx (implementacion), ComponentName/ComponentName.module.css (estilos), ComponentName/ComponentName.test.tsx (tests) y ComponentName/ComponentName.stories.tsx (Storybook).",
            "### 4.3 Gestion de Estado con Zustand",
            "Para el estado global de la aplicacion, usamos Zustand. Redux esta explicitamente prohibido en proyectos nuevos. Zustand se prefiere por su API minimalista, su compatibilidad con TypeScript y la ausencia de boilerplate.",
            "El estado del servidor (datos fetcheados de la API) no debe vivir en Zustand: para eso usamos React Query (TanStack Query) que provee cache, revalidacion automatica y estados de loading/error de forma declarativa.",
            "### 4.4 Data Fetching con TanStack Query",
            "TanStack Query (anteriormente React Query) es la herramienta estandar para manejo de estado del servidor. Cada query debe tener una queryKey descriptiva que incluya todos los parametros que la hacen unica. El objeto de configuracion global del QueryClient corporativo esta en /lib/query-client.ts de la plantilla de proyecto.",
            "---",
            "## 5. CSS y Estilos",
            "### 5.1 CSS Modules",
            "CSS Modules es nuestro enfoque principal para estilos. Los archivos de modulos CSS tienen la extension .module.css y sus clases son localmente escopadas al componente, evitando colisiones de nombres. Tailwind CSS esta prohibido en proyectos nuevos para mantener control granular del diseno.",
            "### 5.2 Variables CSS",
            "Los tokens del Design System (colores, tipografia, espaciado) estan definidos como Custom Properties (variables CSS) en un archivo global (:root { ... }). Los componentes deben referenciar estas variables en lugar de usar valores hardcodeados.",
            "### 5.3 Animaciones y Transiciones",
            "Las animaciones deben ser sutiles y significativas. Regla general: transiciones de 150-300ms para micro-interacciones (hover, focus), y 300-500ms para transiciones de pagina o modales. Siempre respetar prefers-reduced-motion para usuarios con sensibilidad al movimiento.",
            "---",
            "## 6. Testing",
            "### 6.1 Unit Testing con Vitest y React Testing Library",
            "Para proyectos con Vite usamos Vitest + React Testing Library. Para proyectos con Next.js usamos Jest + React Testing Library. La filosofia de testing es: testear el comportamiento, no la implementacion. Los tests no deben saber como esta construido un componente internamente.",
            "### 6.2 Visual Regression Testing con Chromatic",
            "Los componentes del Design System tienen tests de regresion visual automatizados usando Storybook + Chromatic. Cada PR que modifica un componente del design system dispara una revision visual en Chromatic antes de poder mergear.",
            "### 6.3 End-to-End Testing con Playwright",
            "Los flujos criticos del negocio (registro de usuario, checkout, login) tienen tests E2E escritos con Playwright. Los tests de Playwright corren en el pipeline de CI contra el entorno de staging. Un fallo en los tests E2E bloquea el deploy a produccion.",
            "---",
            "## 7. Performance",
            "### 7.1 Core Web Vitals",
            "El equipo de Front-end hace seguimiento continuo de los Core Web Vitals: LCP (Largest Contentful Paint, objetivo menor a 2.5s), FID/INP (Interaction to Next Paint, objetivo menor a 200ms) y CLS (Cumulative Layout Shift, objetivo menor a 0.1). Los dashboards de CWV estan en Grafana.",
            "### 7.2 Code Splitting y Lazy Loading",
            "Todas las rutas de Next.js hacen code splitting automatico. Para componentes pesados dentro de una pagina (graficos, editores de texto rico, mapas), se debe usar React.lazy() + Suspense para cargarlos de forma diferida. Las imagenes siempre deben usar el componente Image de Next.js para optimizacion automatica.",
            "### 7.3 Bundle Analysis",
            "Periodicamente se analiza el tamano del bundle con @next/bundle-analyzer. Ninguna dependencia de mas de 50KB (minificada + gzip) puede agregarse sin aprobacion del Tech Lead.",
            "---",
            "## 8. Accesibilidad (a11y)",
            "### 8.1 Estandar WCAG 2.1 AA",
            "Toda interfaz publica de Da&amp;Da Solutions debe cumplir el nivel AA de las WCAG 2.1. Los criterios mas importantes son: contraste de color minimo 4.5:1 para texto normal, toda funcionalidad debe ser operable con teclado, todos los elementos interactivos deben tener un aria-label descriptivo cuando no tienen texto visible.",
            "### 8.2 Herramientas de Auditoria",
            "Usamos axe-core (integrado en los tests de React Testing Library con @testing-library/jest-axe) para detectar violaciones de accesibilidad de forma automatica. Tambien realizamos auditorias manuales usando lectores de pantalla como NVDA y VoiceOver.",
            "---",
            "## 9. Internacionalizacion (i18n)",
            "Para aplicaciones multi-idioma, usamos la libreria next-intl (para proyectos Next.js) o i18next (para SPAs con Vite). Todas las cadenas de texto visibles al usuario deben estar externalizadas en archivos de traduccion JSON por idioma. Nunca se deben escribir strings de UI directamente en el codigo JSX/TSX.",
            "---",
            "## 10. Despliegue y Entornos",
            "Las aplicaciones front-end se despliegan en dos plataformas segun su tipo: Vercel (para aplicaciones Next.js publicas) y un bucket S3 + CloudFront (para SPAs internas). El pipeline de CI/CD es identico al del back-end: cada PR dispara tests automatizados, y el merge a main desencadena el deploy automatico al entorno correspondiente.",
        ],
    },

    # --------------------------------------------------------------------------
    # 4. MICROSERVICES ARCHITECTURE
    # --------------------------------------------------------------------------
    {
        "filename": "microservices_architecture.pdf",
        "title": "Arquitectura de Microservicios en Da&Da Solutions",
        "subtitle": "Vision general, patrones de diseno y estandares para sistemas distribuidos",
        "content": [
            "## 1. Introduccion a la Arquitectura Distribuida",
            "Da&amp;Da Solutions migro de un monolito a una arquitectura de microservicios en 2019. Esta decision fue motivada por la necesidad de escalar equipos de forma independiente, poder deployar componentes individuales sin afectar al sistema completo y adoptar la tecnologia mas adecuada para cada dominio de negocio (polyglot persistence y polyglot programming).",
            "Este documento describe los principios, patrones y estandares que rigen la arquitectura de microservicios en Da&amp;Da Solutions. Es lectura obligatoria para todos los ingenieros que disenien, desarrollen u operen servicios en nuestra plataforma.",
            "---",
            "## 2. Principios de Diseno",
            "### 2.1 Single Responsibility",
            "Cada microservicio es responsable de un unico dominio de negocio. Un servicio no debe conocer los detalles internos de otro servicio. Solo se comunican a traves de sus APIs o eventos publicados. Si un servicio necesita datos de otro, los solicita explicitamente.",
            "### 2.2 Autonomia y Aislamiento de Datos",
            "Cada microservicio es dueno de su base de datos. Ningun servicio puede acceder directamente a la base de datos de otro servicio. Si el servicio A necesita datos del dominio B, debe consultar al servicio B a traves de su API. El patron de 'base de datos compartida' esta explicitamente prohibido.",
            "### 2.3 Resiliencia ante Fallos",
            "En un sistema distribuido, los fallos son inevitables. Cada servicio debe ser disenado asumiendo que sus dependencias pueden fallar. Los patrones de resiliencia (Circuit Breaker, Retry con backoff exponencial, Timeout, Bulkhead) no son opcionales: son parte del estandar de calidad.",
            "### 2.4 Design for Failure",
            "Cada trimestre ejecutamos ejercicios de Chaos Engineering en el entorno de staging para verificar que los mecanismos de resiliencia funcionan correctamente bajo condiciones de fallo reales.",
            "---",
            "## 3. Catalogo de Servicios",
            "### 3.1 Core Services",
            "Los servicios core de la plataforma son los que sustentan la funcionalidad principal del negocio:",
            "- <b>auth-service:</b> Gestion de usuarios, autenticacion JWT y OAuth 2.0. Python/FastAPI. PostgreSQL.",
            "- <b>user-profile-service:</b> Perfiles de usuario, preferencias y configuraciones. Node.js/NestJS. PostgreSQL.",
            "- <b>billing-service:</b> Facturacion, suscripciones y pagos. Python/FastAPI. PostgreSQL. Integra con Stripe.",
            "- <b>notification-service:</b> Envio de emails (SendGrid), SMS (Twilio) y notificaciones push. Node.js. Redis.",
            "- <b>product-catalog-service:</b> Catalogo de productos y servicios. Node.js/NestJS. MongoDB.",
            "- <b>analytics-service:</b> Procesamiento y consulta de eventos de analitica. Python. ClickHouse.",
            "### 3.2 Platform Services",
            "- <b>api-gateway:</b> Punto de entrada unico para el cliente. Rate limiting, autenticacion, enrutamiento. Go.",
            "- <b>service-mesh:</b> Implementado con Istio para gestion de trafico interno, mTLS y observabilidad.",
            "- <b>config-service:</b> Distribucion centralizada de configuracion usando Consul.",
            "---",
            "## 4. Comunicacion Entre Servicios",
            "### 4.1 Comunicacion Asincrona con Apache Kafka",
            "La comunicacion asincrona es la norma en Da&amp;Da Solutions. Utilizamos Apache Kafka como backbone de eventos. Los servicios publican eventos a topicos de Kafka cuando ocurren cambios en su dominio. Otros servicios se suscriben a los topicos relevantes y reaccionan a esos eventos.",
            "Los eventos deben ser disenados como 'notification events' (el servicio notifica que algo ocurrio) o 'event-carried state transfer' (el evento lleva el estado completo del objeto).",
            "### 4.2 Convenciones de Topicos de Kafka",
            "Los nombres de topicos siguen el formato: {dominio}.{entidad}.{evento}. Ejemplos: billing.invoice.created, user.account.deactivated, order.shipment.dispatched. Cada topico tiene al menos 3 particiones para permitir paralelismo de consumo.",
            "Los mensajes en Kafka deben serializarse en formato <b>Apache Avro</b> con schema definido en el Schema Registry. Esto garantiza la compatibilidad evolutiva de los contratos.",
            "### 4.3 Comunicacion Sincrona con gRPC",
            "Para los casos donde la comunicacion sincrona es estrictamente necesaria (bajo latencia requerida, respuesta inmediata), usamos gRPC sobre HTTP/2. gRPC ofrece una definicion de contrato tipada (Protocol Buffers), streaming bidireccional y mejor performance que REST. Los archivos .proto viven en el repositorio centralizado dada-solutions/proto-registry.",
            "### 4.4 Comunicacion Sincrona con REST",
            "Para servicios que no requieren la performance de gRPC y donde la simplicidad es prioritaria, usamos REST. La comunicacion REST interna usa el mismo SDK de cliente generado desde la especificacion OpenAPI del servicio.",
            "---",
            "## 5. Patrones de Resiliencia",
            "### 5.1 Circuit Breaker",
            "El patron Circuit Breaker previene que un fallo en un servicio dependiente cause una cascada de fallos en todo el sistema. Usamos la libreria Resilience4j (Java/Kotlin) y tenacity (Python). Los estados del Circuit Breaker son CLOSED (funcionamiento normal), OPEN (fallas detectadas, se rechaza trafico) y HALF-OPEN (prueba de recuperacion).",
            "### 5.2 Retry con Backoff Exponencial y Jitter",
            "Todas las llamadas a servicios externos deben implementar retries con backoff exponencial y jitter aleatorio. El jitter es esencial para evitar el problema de 'thundering herd'. La formula de backoff es: delay = min(cap, base * 2^attempt) + random_jitter.",
            "### 5.3 Timeout",
            "Todo cliente HTTP o de base de datos debe configurar un timeout explicito. El timeout por defecto en comunicaciones sincronas es de 5 segundos para APIs de usuario y 30 segundos para procesos de batch.",
            "### 5.4 Bulkhead",
            "El patron Bulkhead aisla los recursos (thread pools, connection pools) por dependencia. Si una dependencia lenta agota el pool de conexiones, no debe afectar a otras dependencias.",
            "---",
            "## 6. API Gateway",
            "### 6.1 Funciones del API Gateway",
            "El API Gateway es el unico punto de entrada al sistema para los clientes externos. Sus responsabilidades son: enrutamiento de requests al microservicio correspondiente, validacion de tokens JWT, rate limiting por cliente/IP, transformacion de requests y terminacion TLS.",
            "### 6.2 Rate Limiting",
            "El rate limiting se implementa a nivel del API Gateway. Las reglas por defecto son: 1000 requests por minuto por usuario autenticado y 100 requests por minuto por IP no autenticada.",
            "### 6.3 No Logica de Negocio en el Gateway",
            "El API Gateway es un componente de infraestructura, no de negocio. No debe contener logica de negocio, transformaciones complejas de datos ni agregaciones. Si se necesita agregar datos de multiples servicios, el patron correcto es el BFF (Backend For Frontend).",
            "---",
            "## 7. Service Mesh con Istio",
            "### 7.1 Gestion de Trafico Interno",
            "Istio gestiona el trafico entre microservicios dentro del cluster de Kubernetes. Provee: balanceo de carga inteligente, retries y timeouts configurables a nivel de infra (sin codigo), circuit breaking y canary deployments con control granular del porcentaje de trafico.",
            "### 7.2 mTLS Entre Servicios",
            "Istio habilita Mutual TLS (mTLS) entre todos los servicios del mesh. Esto significa que la comunicacion entre servicios esta cifrada y autenticada mutuamente. Ningun servicio puede hacer una llamada a otro sin presentar un certificado valido gestionado por Istio.",
            "---",
            "## 8. Saga Pattern para Transacciones Distribuidas",
            "### 8.1 El Problema de las Transacciones ACID en Microservicios",
            "En una arquitectura de microservicios, las transacciones que abarcan multiples servicios no pueden usar ACID tradicional. El patron Saga divide una transaccion larga en pasos locales coordinados con mecanismos de compensacion para deshacer el trabajo en caso de fallo.",
            "### 8.2 Coreografia vs Orquestacion",
            "Da&amp;Da Solutions usa ambos estilos de Saga segun el caso. Para procesos simples, usamos <b>coreografia</b>: cada servicio escucha eventos y reacciona emitiendo los suyos. Para procesos complejos (como el proceso de checkout que involucra 5+ servicios), usamos <b>orquestacion</b> con un Saga Orchestrator explicito.",
            "---",
            "## 9. Estrategia de Deployments",
            "### 9.1 Blue/Green Deployments",
            "Para servicios criticos donde el tiempo de downtime es inaceptable, usamos Blue/Green Deployments. Se mantienen dos entornos de produccion identicos (Blue y Green). El trafico se redirige atomicamente de uno al otro. El rollback es instantaneo.",
            "### 9.2 Canary Deployments",
            "Para validar cambios en produccion con trafico real pero controlado, usamos Canary Deployments a traves de Istio. El proceso es: 5% del trafico a la nueva version, observar metricas durante 30 minutos, si las metricas son sanas escalar al 25%, luego al 50%, luego al 100%.",
            "---",
            "## 10. Catalogo de Decisiones de Arquitectura (ADRs)",
            "Todas las decisiones de arquitectura significativas en Da&amp;Da Solutions se documentan como Architecture Decision Records (ADRs). Un ADR describe el contexto, las opciones consideradas, la decision tomada y sus consecuencias. El repositorio de ADRs esta en dada-solutions/architecture-decisions en GitHub.",
            "Antes de proponer una nueva tecnologia o patron significativo, se debe abrir un draft de ADR para discutirlo con el equipo de arquitectura. Nadie toma decisiones de arquitectura de forma unilateral.",
        ],
    },

    # --------------------------------------------------------------------------
    # 5. DEVOPS / CI-CD
    # --------------------------------------------------------------------------
    {
        "filename": "devops_cicd.pdf",
        "title": "Manual de DevOps y CI/CD",
        "subtitle": "Guia completa de operaciones, despliegues, monitoreo y cultura DevOps en Da&Da Solutions",
        "content": [
            "## 1. Cultura DevOps en Da&Da Solutions",
            "DevOps en Da&amp;Da Solutions no es un equipo ni un cargo: es una cultura compartida entre ingenieria y operaciones. El equipo de Platform Engineering proporciona las herramientas, la plataforma y el soporte, pero cada squad es responsable de operar sus propios servicios en produccion. 'You build it, you run it' es nuestro mantra.",
            "Esta responsabilidad compartida crea mejores productos: un equipo que opera lo que construye tiene incentivos naturales para construirlo de forma mas confiable, observable y operable.",
            "---",
            "## 2. Contenedores y Containerizacion",
            "### 2.1 Docker como Estandar",
            "Todos los servicios de Da&amp;Da Solutions deben estar contenerizados con Docker. La imagen Docker es el artefacto de deployment. El mismo artefacto se prueba en CI, se promueve a staging y luego a produccion. Esto garantiza el principio de 'build once, deploy everywhere'.",
            "### 2.2 Mejores Practicas de Dockerfile",
            "El Dockerfile de cada servicio debe seguir las siguientes practicas: usar imagenes base oficiales y minimas (preferir alpine o distroless), multi-stage builds para reducir el tamano de la imagen final, no correr el proceso principal como root (crear un usuario no-privilegiado), y especificar siempre el HEALTHCHECK instruction.",
            "### 2.3 Escaneo de Vulnerabilidades",
            "Todas las imagenes Docker son escaneadas automaticamente con Trivy en el pipeline de CI. Una imagen con vulnerabilidades CRITICAL no puede ser promovida a produccion. Las vulnerabilidades HIGH son documentadas como excepciones temporales con fecha de resolucion maxima de 30 dias.",
            "---",
            "## 3. Kubernetes (K8s)",
            "### 3.1 Clusteres de Kubernetes",
            "Da&amp;Da Solutions opera tres clusteres de Kubernetes en Google Kubernetes Engine (GKE): uno para Development/QA, uno para Staging y uno para Production. Los clusteres de staging y produccion son Multi-AZ (multi-zona) para garantizar alta disponibilidad.",
            "### 3.2 Namespaces",
            "Dentro de cada cluster, los servicios se organizan en namespaces. Los namespaces estandar son: platform (servicios de infraestructura como Istio, cert-manager), data (servicios del area de datos), y un namespace por squad de producto (ej: squad-billing, squad-catalog).",
            "### 3.3 Resource Requests y Limits",
            "Todos los Pods de Kubernetes deben tener configurados Resource Requests y Limits de CPU y memoria. Los Requests deben ser calibrados al consumo promedio real del servicio; los Limits deben ser calibrados al pico maximo observado. Un Pod sin Resource Requests en el namespace de produccion es rechazado por un Admission Webhook.",
            "### 3.4 Horizontal Pod Autoscaler (HPA)",
            "Los servicios con carga variable deben configurar HPA. La metrica principal para escalar es CPU Utilization con un target del 70%. Para servicios basados en colas (workers de Kafka), usamos KEDA (Kubernetes Event-Driven Autoscaling) para escalar basandose en el lag del consumer group.",
            "### 3.5 Pod Disruption Budgets (PDB)",
            "Para garantizar la disponibilidad durante los rolling updates, todos los servicios con mas de un replica deben tener un PodDisruptionBudget que garantice que al menos el 50% de los pods esten disponibles en todo momento.",
            "---",
            "## 4. GitOps con ArgoCD",
            "### 4.1 Que es GitOps?",
            "GitOps es el paradigma de operaciones donde el estado deseado de la infraestructura y las aplicaciones esta definido de forma declarativa en un repositorio Git. ArgoCD es el operador de Kubernetes que implementa GitOps: sincroniza continuamente el estado del cluster con lo que esta definido en el repositorio.",
            "### 4.2 Repositorio de Manifiestos",
            "El repositorio dada-solutions/k8s-manifests contiene todos los manifiestos de Kubernetes (Deployments, Services, ConfigMaps, HPA, etc.) organizados por cluster y namespace. Este repositorio es la fuente de verdad de lo que esta corriendo en produccion.",
            "### 4.3 Proceso de Promocion entre Entornos",
            "El flujo de promocion es: el pipeline de CI construye la imagen Docker y actualiza el tag en el manifiesto del entorno de Development. El equipo de QA valida en Development. Cuando se aprueba, se hace un PR para actualizar el tag en el manifiesto de Staging. ArgoCD detecta el cambio y despliega automaticamente.",
            "---",
            "## 5. Pipelines de CI/CD con GitHub Actions",
            "### 5.1 Pipeline de Integracion Continua (CI)",
            "Cada PR dispara el pipeline de CI automaticamente. Los pasos del pipeline de CI son:",
            "- <b>Lint:</b> Verificacion de estilo de codigo (ruff para Python, ESLint para JS/TS).",
            "- <b>Type Check:</b> Verificacion de tipos (mypy para Python, tsc para TypeScript).",
            "- <b>Unit Tests:</b> Ejecucion de tests unitarios con reporte de cobertura.",
            "- <b>Integration Tests:</b> Ejecucion de tests de integracion con servicios en contenedores.",
            "- <b>Security Scan (SAST):</b> Analisis estatico de seguridad con Bandit/Semgrep.",
            "- <b>Docker Build:</b> Construccion de la imagen Docker.",
            "- <b>Docker Scan:</b> Escaneo de vulnerabilidades con Trivy.",
            "### 5.2 Pipeline de Despliegue Continuo (CD)",
            "El pipeline de CD se dispara automaticamente con cada merge a la rama main. Los pasos son: construccion de la imagen Docker de produccion, push al Container Registry (Google Artifact Registry), actualizacion del tag de imagen en el repositorio de manifiestos de Kubernetes y notificacion al canal #deployments de Slack.",
            "### 5.3 GitHub Actions: Seguridad",
            "Para garantizar la seguridad de los pipelines: usar siempre versiones fijadas de Actions (ej: actions/checkout@v4.1.1, no @v4 ni @main), nunca imprimir secretos en los logs, usar GitHub Secrets o OIDC para autenticacion con proveedores cloud (no usar access keys estaticas).",
            "---",
            "## 6. Gestion de Secretos en Produccion",
            "### 6.1 HashiCorp Vault",
            "Todos los secretos en produccion (contrasenas de base de datos, API keys externas, certificados TLS) son gestionados por HashiCorp Vault. Los Pods de Kubernetes obtienen sus secretos al momento de inicializarse a traves del Vault Agent Injector.",
            "### 6.2 Rotacion Automatica de Secretos",
            "Vault gestiona la rotacion automatica de credenciales de bases de datos (PostgreSQL dynamic secrets) cada 24 horas. Los servicios que usan credenciales dinamicas deben implementar la logica de renovacion del lease.",
            "---",
            "## 7. Monitoreo y Observabilidad",
            "### 7.1 El Stack de Observabilidad",
            "El stack de observabilidad de Da&amp;Da Solutions se basa en el estandar de la industria conocido como 'The Three Pillars of Observability': Metricas (Prometheus + Grafana), Logs (Loki + Grafana) y Trazas (Tempo + Grafana). Todo el stack es accesible a traves del dashboard unificado de Grafana.",
            "### 7.2 Alertas con AlertManager",
            "Las alertas de Prometheus son configuradas en archivos de reglas (PrometheusRule). Cuando se dispara una alerta, AlertManager la enruta al canal de Slack correspondiente o a PagerDuty para alertas de severidad P1.",
            "### 7.3 Dashboards de Grafana",
            "Cada servicio debe tener un dashboard de Grafana con las metricas basicas: latencia (percentiles P50, P95, P99), tasa de errores, throughput, y metricas de recursos (CPU y memoria).",
            "### 7.4 SLOs y SLAs",
            "Cada servicio critico tiene SLOs (Service Level Objectives) definidos. Los SLOs mas comunes son: Availability del 99.9% mensual, Latencia P99 menor a 500ms y Error Rate menor al 0.1%. El incumplimiento de SLOs desencadena post-mortems obligatorios.",
            "---",
            "## 8. Manejo de Incidentes",
            "### 8.1 Severidades",
            "Los incidentes se clasifican en cuatro niveles: P1 (servicio critico completamente caido, impacto en todos los usuarios), P2 (degradacion significativa de un servicio critico), P3 (degradacion menor o impacto en un subconjunto pequeno de usuarios) y P4 (bug o degradacion con workaround disponible).",
            "### 8.2 Proceso de Respuesta a Incidentes",
            "El proceso de respuesta: 1) Deteccion (automatizada por alertas o reporte de usuario). 2) Notificacion en #incidentes. 3) Asignacion de Incident Commander (IC). 4) Mitigacion (prioridad: restaurar el servicio, no encontrar la causa raiz). 5) Resolucion. 6) Post-mortem dentro de las 48 horas.",
            "### 8.3 Post-Mortems",
            "Todo incidente P1 o P2 requiere un post-mortem escrito dentro de las 48 horas. El post-mortem sigue el formato blameless de Google SRE: linea de tiempo de eventos, causa raiz, impacto, acciones de remediacion inmediata y acciones de prevencion a largo plazo.",
            "---",
            "## 9. Infraestructura como Codigo (IaC) con Terraform",
            "Toda la infraestructura cloud de Da&amp;Da Solutions esta definida en codigo usando Terraform. Los modulos de Terraform viven en el repositorio dada-solutions/infrastructure. Los cambios de infraestructura siguen el mismo proceso que los cambios de codigo: PR, revision y merge. Nunca se hacen cambios manuales a la infraestructura de produccion desde la consola cloud.",
            "---",
            "## 10. Ambientes de Desarrollo y Staging",
            "### 10.1 Entorno de Development",
            "El entorno de Development esta disponible para todos los equipos para probar cambios sin afectar a usuarios reales. Los deployments a Development son automaticos con cada PR. Los datos en Development son datos sinteticos generados por el equipo de QA.",
            "### 10.2 Entorno de Staging",
            "Staging es una replica fiel de produccion en cuanto a configuracion de infraestructura. Los datos de Staging son una copia anonimizada de los datos de produccion, actualizada cada semana. Todos los cambios deben ser validados en Staging antes de deployar a produccion. Los tests E2E de Playwright corren automaticamente en Staging en cada deployment.",
        ],
    },

    # --------------------------------------------------------------------------
    # 6. DATA PERSISTENCE
    # --------------------------------------------------------------------------
    {
        "filename": "data_persistence.pdf",
        "title": "Guia de Persistencia de Datos",
        "subtitle": "Estandares de modelado, almacenamiento y gestion de datos en Da&Da Solutions",
        "content": [
            "## 1. Filosofia de Gestion de Datos",
            "En Da&amp;Da Solutions, los datos son el activo mas valioso de la empresa y de nuestros clientes. Toda decision sobre como almacenar, procesar y proteger datos debe tomarse con el maximo rigor. Este documento establece los estandares para la persistencia de datos en todos los servicios de la compania.",
            "El principio guia es: elegir la herramienta correcta para el problema correcto. No existe una base de datos universal que sea optima para todos los casos de uso. La clave esta en entender las caracteristicas de cada motor y elegir el mas adecuado para el patron de acceso y la naturaleza de los datos de cada servicio.",
            "---",
            "## 2. Bases de Datos Relacionales: PostgreSQL",
            "### 2.1 Cuando Usar PostgreSQL",
            "PostgreSQL es la base de datos por defecto para la gran mayoria de los servicios de Da&amp;Da Solutions. Se elige cuando: los datos tienen relaciones complejas entre entidades, la integridad referencial es critica (facturacion, finanzas, inventario, gestion de usuarios), se necesitan transacciones ACID complejas que abarcan multiples entidades, o el dominio de negocio requiere consultas analiticas complejas con joins.",
            "### 2.2 Version y Configuracion",
            "La version minima de PostgreSQL soportada es la 15. Toda base de datos de produccion tiene: max_connections configurado segun el numero de workers del servicio + overhead de pgBouncer, work_mem calibrado para las queries mas complejas del servicio, y shared_buffers en el 25% de la RAM disponible como punto de partida.",
            "### 2.3 Gestion de Esquema y Migraciones",
            "Las migraciones de esquema son la parte mas critica y peligrosa del ciclo de vida de la base de datos. Reglas de oro:",
            "- <b>Alembic</b> (Python) o <b>Prisma Migrate</b> (Node.js) son las unicas herramientas de migracion aprobadas.",
            "- Nunca se ejecutan migraciones manuales en produccion. Todas las migraciones se ejecutan automaticamente como parte del proceso de deployment.",
            "- Las migraciones deben ser backward-compatible. Nunca borrar una columna o tabla sin haberla deprecado primero en un release anterior; nunca agregar columnas con NOT NULL sin default value.",
            "### 2.4 Conexion y Connection Pooling",
            "PostgreSQL tiene un limite natural de conexiones concurrentes. Para gestionar eficientemente las conexiones, todos los servicios se conectan a traves de <b>PgBouncer</b> (connection pooler) en modo transaction pooling.",
            "### 2.5 Indices",
            "Los indices mal disenados pueden ser tan daninos como no tenerlos. Reglas:",
            "- Crear indices para columnas usadas en clausulas WHERE, JOIN, ORDER BY y GROUP BY.",
            "- Usar indices parciales cuando la mayoria de las filas de la tabla no seran consultadas por ese indice.",
            "- Monitorear regularmente los indices no usados (pg_stat_user_indexes) y eliminarlos.",
            "- Agregar indices en produccion siempre usando CREATE INDEX CONCURRENTLY para no bloquear la tabla.",
            "### 2.6 Backups y Recuperacion",
            "Los backups de PostgreSQL en produccion se realizan con pgBackRest y se almacenan en Google Cloud Storage con retencion de 30 dias. Los backups son: WAL archiving continuo (RPO: minutos), backups completos diarios, y backups incrementales cada 4 horas.",
            "---",
            "## 3. Bases de Datos Documentales: MongoDB",
            "### 3.1 Cuando Usar MongoDB",
            "MongoDB se usa cuando: el esquema de los datos es dinamico o variable (catalogos de productos con atributos diferentes por categoria), los datos se consultan casi siempre como un documento completo sin necesidad de joins, se requiere alta velocidad de escritura, o la estructura de los datos es jerarquica.",
            "### 3.2 Modelo de Datos: Embedding vs. Referencing",
            "La decision mas importante en el modelado de MongoDB es cuando embeber documentos y cuando referenciarlos:",
            "- <b>Embeber</b> cuando: la relacion es 1-a-pocos, los datos embebidos siempre se consultan juntos al documento padre, los datos embebidos no cambian frecuentemente de forma independiente.",
            "- <b>Referenciar</b> cuando: la relacion es muchos-a-muchos, los datos referenciados son muy grandes y no siempre se necesitan, los datos referenciados se consultan frecuentemente de forma independiente.",
            "### 3.3 Indices en MongoDB",
            "Igual que en SQL, los indices son criticos para el rendimiento. Indices obligatorios en MongoDB: crear indice en los campos usados en los filtros mas frecuentes, usar indices compuestos para consultas con multiples campos en el filtro y monitorear las queries con explain('executionStats') para verificar que estan usando indices.",
            "### 3.4 Version y Cluster",
            "La version minima soportada es MongoDB 7.0. En produccion usamos MongoDB Atlas (servicio gestionado), con cluster M30 como minimo. La configuracion de replica set es obligatoria (minimo 3 nodos) para garantizar la disponibilidad.",
            "---",
            "## 4. Cache en Memoria: Redis",
            "### 4.1 Casos de Uso de Redis en Da&Da Solutions",
            "Redis se usa en Da&amp;Da Solutions para cuatro propositos principales:",
            "- <b>Cache de datos:</b> Resultados de consultas costosas a la base de datos con patrones de lectura frecuente.",
            "- <b>Gestion de sesiones:</b> Almacenamiento de Refresh Tokens con TTL automatico.",
            "- <b>Rate limiting:</b> Contadores de requests por usuario/IP usando el algoritmo Sliding Window con Redis Sorted Sets.",
            "- <b>Colas de trabajo:</b> Colas de tareas asincronas usando la estructura de datos Stream de Redis o BullMQ (Node.js).",
            "### 4.2 Configuracion y Politicas de Eviccion",
            "La politica de eviccion por defecto en Redis para cache es <b>allkeys-lru</b>. Para Redis usado como store de sesiones (donde no se puede perder datos), la politica es <b>noeviction</b> con monitoreo de memoria y alertas.",
            "Toda clave en Redis debe tener un TTL (Time To Live) explicito, excepto casos muy especificos y justificados. Un Redis sin TTLs es una bomba de tiempo de memoria.",
            "### 4.3 Alta Disponibilidad con Redis Sentinel/Cluster",
            "En produccion, Redis corre en modo Redis Cluster (para cargas que requieren sharding) o con Redis Sentinel (para alta disponibilidad sin sharding). En Da&amp;Da Solutions usamos Google Memorystore for Redis que gestiona esto de forma transparente.",
            "---",
            "## 5. Almacenamiento Analitico: ClickHouse",
            "### 5.1 Para que Sirve ClickHouse",
            "ClickHouse es una base de datos columnar orientada a analitica (OLAP). Se usa en Da&amp;Da Solutions para: almacenamiento y consulta de eventos de analitica de producto (millones/billones de filas), dashboards en tiempo real, y cualquier consulta analitica sobre grandes volumenes de datos donde PostgreSQL seria demasiado lento.",
            "### 5.2 Modelo de Datos Columnar",
            "A diferencia de las bases de datos orientadas a filas (OLTP), ClickHouse almacena los datos por columnas. Esto es extremadamente eficiente para consultas analiticas que leen pocas columnas de millones de filas. El tipo de tabla MergeTree y sus variantes (ReplacingMergeTree, AggregatingMergeTree) son los mas usados.",
            "---",
            "## 6. Almacenamiento de Objetos: Google Cloud Storage",
            "Google Cloud Storage (GCS) es el almacenamiento de objetos estandar para Da&amp;Da Solutions. Se usa para: almacenamiento de archivos subidos por usuarios (imagenes, documentos, videos), backups de bases de datos, artefactos de CI/CD, y datasets de entrenamiento para modelos de ML.",
            "Los buckets de produccion tienen: versionado habilitado (para recuperar versiones anteriores de archivos), Object Lifecycle Management para mover datos frios a Storage Classes mas baratos, y Data Loss Prevention (DLP) scanning para detectar PII inadvertidamente almacenado.",
            "---",
            "## 7. Proteccion y Privacidad de Datos",
            "### 7.1 Clasificacion de Datos",
            "Da&amp;Da Solutions clasifica los datos en cuatro niveles: PUBLICO (puede ser compartido libremente), INTERNO (acceso limitado a empleados), CONFIDENCIAL (acceso restringido) y RESTRINGIDO (maxima proteccion: datos personales de usuarios, informacion financiera).",
            "### 7.2 Datos Personales y GDPR/LGPD",
            "Los datos personales de usuarios son la categoria mas sensible. Los principios aplicados son: minimizacion de datos (solo recolectar los datos estrictamente necesarios), limitacion de proposito (no usar los datos para fines distintos a los declarados), integridad y confidencialidad (cifrar datos sensibles en reposo y en transito), y derechos del titular (implementar mecanismos para acceder, rectificar y eliminar datos).",
            "### 7.3 Cifrado en Reposo",
            "Todos los datos en bases de datos de produccion estan cifrados en reposo usando AES-256. Google Cloud gestiona las claves de cifrado por defecto; para datos de maxima sensibilidad, usamos Customer-Managed Encryption Keys (CMEK) con claves gestionadas en Google Cloud KMS.",
            "---",
            "## 8. Estrategia de Backups",
            "Los backups siguen la estrategia 3-2-1: al menos 3 copias de los datos, en 2 tipos de almacenamiento diferentes, con 1 copia offsite (en una region de nube diferente). Los backups se prueban restaurando en un entorno de prueba al menos una vez por trimestre.",
            "El RTO (Recovery Time Objective) objetivo para restauracion de datos es de 4 horas para P1. El RPO (Recovery Point Objective) objetivo es de 1 hora para bases de datos transaccionales. Cualquier incumplimiento de estos objetivos se reporta como incidente de severidad P1.",
        ],
    },

    # --------------------------------------------------------------------------
    # 7. AI AGENTS
    # --------------------------------------------------------------------------
    {
        "filename": "ai_agents.pdf",
        "title": "Desarrollo de Agentes de IA y LLMs",
        "subtitle": "Estandares, patrones y mejores practicas para la implementacion de Inteligencia Artificial en Da&Da Solutions",
        "content": [
            "## 1. Vision de IA en Da&Da Solutions",
            "Da&amp;Da Solutions tiene una apuesta estrategica por la Inteligencia Artificial como diferenciador competitivo. No como una moda, sino como una capacidad tecnica real que agrega valor medible a nuestros productos y a nuestros clientes. El equipo de AI Engineering trabaja embebido en los squads de producto para disenar e implementar soluciones de IA responsables, robustas y escalables.",
            "Este documento establece los estandares tecnicos y eticos que rigen todo el desarrollo de IA en Da&amp;Da Solutions. Su lectura es obligatoria para cualquier ingeniero que trabaje con LLMs, embeddings, sistemas de recomendacion o cualquier componente de Machine Learning.",
            "---",
            "## 2. Modelos Fundacionales (LLMs) Aprobados",
            "### 2.1 Google Gemini",
            "Google Gemini es nuestro LLM primario. Usamos distintas variantes segun la necesidad:",
            "- <b>gemini-2.0-flash:</b> Tareas de razonamiento y generacion de texto de alta calidad. El modelo de referencia para aplicaciones de produccion.",
            "- <b>gemini-1.5-flash:</b> Version mas economica para tareas de alta frecuencia donde la velocidad y el costo son prioritarios.",
            "- <b>gemini-embedding-004:</b> Modelo de embeddings estandar para RAG y busqueda semantica.",
            "### 2.2 Cohere",
            "Cohere (Command R+) es nuestra segunda opcion para casos donde se requiere RAG de alta precision o cuando Gemini no esta disponible. Cohere tambien provee modelos de embeddings (Embed v3) que son excelentes para busqueda multilingue.",
            "### 2.3 Modelos Open Source (Auto-hosteados)",
            "Para casos de uso que requieren el maximo control sobre los datos (sin envio de datos sensibles a APIs externas) o para reducir costos en alta escala, evaluamos el uso de modelos open source como Llama 3.1 o Mistral Large, hosteados en nuestra infraestructura de GKE con GPUs. El uso de modelos open source en produccion requiere aprobacion del Staff AI Engineer.",
            "---",
            "## 3. Patron RAG (Retrieval-Augmented Generation)",
            "### 3.1 Que es RAG y por que lo usamos?",
            "RAG es el patron arquitectonico estandar en Da&amp;Da Solutions para todas las aplicaciones que requieren que el LLM responda sobre conocimiento especifico de la empresa o del cliente (documentos internos, bases de conocimiento, catalogos de productos). RAG garantiza que las respuestas esten fundamentadas en fuentes verificables, reduce las alucinaciones del LLM y permite actualizar el conocimiento sin reentrenar el modelo.",
            "### 3.2 Arquitectura de un Sistema RAG en Da&Da",
            "La arquitectura estandar de un sistema RAG tiene dos fases: la fase offline (indexacion) y la fase online (inferencia).",
            "<b>Fase de Indexacion (Offline):</b> 1) Carga de documentos fuente (PDFs, paginas web, bases de datos). 2) Chunking del texto en fragmentos manejables. 3) Generacion de embeddings para cada chunk. 4) Almacenamiento en la base de datos vectorial.",
            "<b>Fase de Inferencia (Online):</b> 1) El usuario formula una pregunta. 2) Se genera el embedding de la pregunta. 3) Se buscan los chunks mas similares en la base vectorial (busqueda por similitud coseno). 4) Los chunks mas relevantes se inyectan como contexto en el prompt. 5) El LLM genera la respuesta basandose en ese contexto.",
            "### 3.3 Chunking",
            "La estrategia de chunking es critica para la calidad del RAG. Las reglas en Da&amp;Da Solutions son: usar RecursiveCharacterTextSplitter de LangChain con chunk_size de 1000 caracteres y chunk_overlap de 200 caracteres. El overlap garantiza que no se pierda contexto en los bordes de los chunks.",
            "Para documentos con estructura (PDFs con secciones, codigo fuente), evaluar estrategias de chunking semantico o basado en la estructura del documento (MarkdownTextSplitter, HTMLTextSplitter).",
            "### 3.4 Generacion de Embeddings",
            "Los embeddings deben generarse con el modelo acordado para el proyecto y no mezclarse. Si se cambia el modelo de embeddings, se debe reindexar toda la base vectorial. Para nuevos proyectos, el modelo de embeddings estandar es gemini-embedding-004 de Google.",
            "---",
            "## 4. Bases de Datos Vectoriales",
            "### 4.1 FAISS para Desarrollo Local",
            "FAISS (Facebook AI Similarity Search) es una libreria de indexacion en memoria apropiada para prototipado y desarrollo local. No requiere infraestructura adicional y es muy facil de usar con LangChain. Sin embargo, no es apropiada para produccion: no persiste datos de forma nativa, no escala horizontalmente y no soporta actualizaciones incrementales eficientes.",
            "### 4.2 Qdrant para Produccion",
            "Qdrant es la base de datos vectorial oficial para deployments de produccion en Da&amp;Da Solutions. Las razones de su eleccion son: alta performance en busquedas ANN (Approximate Nearest Neighbor), soporte nativo para filtrado de metadatos junto con la busqueda vectorial, API REST y gRPC completas, y operacion como contenedor en Kubernetes.",
            "Qdrant corre en nuestro cluster de Kubernetes con persistencia en volumenes de Google Persistent Disk. Las colecciones de Qdrant estan respaldadas automaticamente cada 24 horas.",
            "### 4.3 Pinecone como Alternativa",
            "Para casos de uso donde la escala masiva (decenas de millones de vectores) o la simplicidad operativa son prioritarias sobre el control, Pinecone es la alternativa aprobada. Pinecone es un servicio totalmente gestionado (serverless). Su uso debe ser aprobado por el Staff AI Engineer por consideraciones de costo.",
            "---",
            "## 5. Frameworks de Orquestacion",
            "### 5.1 LangChain con LCEL",
            "LangChain es el framework de orquestacion de LLMs estandar en Da&amp;Da Solutions. Usamos LangChain Expression Language (LCEL) para construir chains de procesamiento de forma declarativa y composable. LCEL facilita el streaming de respuestas, el logging con LangSmith y la implementacion de chains RAG complejas.",
            "### 5.2 LangGraph para Agentes Multi-paso",
            "Para aplicaciones que requieren agentes con multiples pasos de razonamiento, uso de herramientas (tools) y ciclos de retroalimentacion, usamos LangGraph. LangGraph modela el flujo del agente como un grafo de estado, lo que permite disenar agentes complejos de forma estructurada y debuggeable.",
            "### 5.3 Cuando NO usar un Framework",
            "Para llamadas simples a la API del LLM sin orquestacion compleja, es valido y recomendado usar directamente el SDK oficial de Google (google-generativeai) sin LangChain. La abstraccion tiene un costo: anade dependencias, complejidad y puede hacer mas dificil el debugging.",
            "---",
            "## 6. Prompt Engineering",
            "### 6.1 Principios de Diseno de Prompts",
            "Un buen prompt es claro, especifico y reproducible. Los principios fundamentales son: dar un rol explicito al modelo ('Eres un asistente experto en...'), proporcionar el contexto necesario, dar instrucciones especificas sobre el formato de salida, incluir ejemplos cuando sea posible (few-shot prompting), y definir las restricciones o limitaciones de la respuesta.",
            "### 6.2 Templates de Prompts en LangChain",
            "Los prompts no deben ser strings hardcodeados en el codigo. Se deben usar PromptTemplate o ChatPromptTemplate de LangChain. Esto permite versionar, testear y reutilizar los prompts. Los prompts de los sistemas mas importantes deben estar almacenados en LangSmith para su monitoreo y versionado.",
            "### 6.3 System Prompts",
            "El System Prompt es el prompt de sistema que define el comportamiento del agente. Reglas para System Prompts en produccion: debe estar versionado en el repositorio, cualquier cambio debe pasar por evaluacion antes de deployar, nunca debe exponer informacion confidencial del sistema ni instrucciones que puedan ser explotadas por prompt injection.",
            "---",
            "## 7. Evaluacion de Sistemas RAG",
            "### 7.1 Por que Evaluar?",
            "Un sistema RAG sin evaluacion sistematica es un sistema sin control de calidad. Las alucinaciones, los errores de recuperacion y las respuestas fuera de contexto pueden pasar inadvertidos sin un framework de evaluacion robusto.",
            "### 7.2 Metricas Clave",
            "Usamos el framework RAGAS para evaluar sistematicamente nuestros sistemas RAG. Las metricas principales son: <b>Faithfulness</b> (la respuesta generada esta fundamentada en el contexto recuperado?), <b>Answer Relevancy</b> (la respuesta es relevante a la pregunta del usuario?), <b>Context Precision</b> (los chunks recuperados son los mas relevantes?) y <b>Context Recall</b> (se recupero todo el contexto necesario para responder?).",
            "### 7.3 Conjunto de Evaluacion (Eval Set)",
            "Cada sistema RAG en produccion debe tener un eval set: un conjunto de pares pregunta-respuesta esperada creado por expertos del dominio. Antes de deployar cualquier cambio al sistema RAG, se debe ejecutar el eval set y comparar las metricas con la linea base.",
            "---",
            "## 8. Observabilidad de Sistemas de IA",
            "### 8.1 LangSmith para Trazabilidad",
            "Todos los sistemas LangChain en produccion estan conectados a LangSmith para trazabilidad completa. LangSmith registra cada invocacion del chain: el prompt completo enviado al LLM, los chunks recuperados de la base vectorial, la respuesta generada, la latencia y el costo en tokens.",
            "### 8.2 Metricas Operacionales",
            "Ademas de LangSmith, los sistemas de IA exponen metricas de Prometheus: latencia de inferencia (P50, P95, P99), tokens por segundo, costo estimado de API por request, y tasa de errores de la API del LLM.",
            "---",
            "## 9. Seguridad y Etica en IA",
            "### 9.1 PII y Datos Sensibles",
            "Bajo ninguna circunstancia deben enviarse datos de identificacion personal (PII) no anonimizados a APIs de LLMs externos (Gemini, Cohere). Si el sistema RAG indexa documentos con PII, estos deben ser anonimizados antes de la indexacion o el sistema debe operarse con modelos self-hosted.",
            "### 9.2 Prompt Injection",
            "El prompt injection es un ataque donde un usuario malicioso inyecta instrucciones en su input para manipular el comportamiento del LLM. Mitigaciones: separar claramente el system prompt de la entrada del usuario, validar y sanitizar el input del usuario antes de enviarlo al LLM, implementar un guardrail de contenido que detecte intentos de injection.",
            "### 9.3 Guardrails de Contenido",
            "Los sistemas de IA de produccion en Da&amp;Da Solutions que interactuan con usuarios finales deben implementar guardrails de contenido usando la libreria NeMo Guardrails o los filtros de seguridad nativos de la API de Gemini. Los guardrails verifican tanto el input del usuario como el output del LLM para detectar contenido inapropiado, informacion personal sensible y respuestas factualmente incorrectas.",
            "### 9.4 IA Responsable",
            "Da&amp;Da Solutions esta comprometida con los principios de IA Responsable: transparencia (el usuario sabe que esta interactuando con un sistema de IA), equidad (los sistemas son evaluados para detectar y mitigar sesgos), y privacidad (minimizacion de datos y respeto a los derechos del usuario).",
            "---",
            "## 10. MLOps y Ciclo de Vida de Modelos",
            "### 10.1 Gestion de Experimentos con MLflow",
            "Para proyectos de ML que involucran entrenamiento de modelos (fine-tuning, modelos de recomendacion, modelos de clasificacion), usamos MLflow para el seguimiento de experimentos. MLflow registra los hiperparametros, las metricas de entrenamiento, los artefactos del modelo y las dependencias de codigo para cada experimento.",
            "### 10.2 Model Registry",
            "Los modelos entrenados se registran en el Model Registry de MLflow antes de cualquier deployment. El flujo de aprobacion es: STAGING (modelo candidato a produccion) -> PRODUCTION (modelo en produccion) -> ARCHIVED (modelo reemplazado). Solo los modelos en estado PRODUCTION son desplegados en los servicios de produccion.",
            "### 10.3 Feature Store",
            "Para proyectos de ML que requieren features computadas en batch y servidas en tiempo real, usamos Feast como Feature Store. Feast garantiza la consistencia entre las features usadas en entrenamiento y las features servidas en inferencia (evitando el training-serving skew).",
        ],
    },
]


# ==============================================================================
if __name__ == "__main__":
    docs_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs")
    os.makedirs(docs_dir, exist_ok=True)

    # Change working directory to project root so "docs/" path works correctly
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(project_root)

    print("=" * 60)
    print("  Da&Da Solutions — Generacion de Documentos Tecnicos")
    print("=" * 60)

    for doc_data in documents:
        create_pdf(
            doc_data["filename"],
            doc_data["title"],
            doc_data["subtitle"],
            doc_data["content"],
        )

    print("=" * 60)
    print("  Todos los documentos generados exitosamente en docs/!")
    print("=" * 60)

